### ISSUE TITLE
db-container-backup.sh fails when MYSQL_ROOT_PASSWORD contains "=" sign

### ISSUE THREAD

**Issue by abobija** [ChristianLempa/scripts#1]
If root password contains `=` sign, script will read just characters before first occurrence of `=` sign. For example if password is `14x=te2`, script will read just `14x`, rest will be ignored.

Solution:

Value of `-f` argument of `cut` command on next two lines should be `2-` (instead of just `2`) in order to `cut` can pick up whole password.

https://github.com/xcad2k/scripts/blob/5e0ed2180cd410bc3eb56300186bdc1f9fda4330/db-container-backup/db-container-backup.sh#L24-L25

So those 2 lines above should looks like this:

```sh
MYSQL_DATABASE=$(docker exec $i env | grep MYSQL_DATABASE |cut -d"=" -f2-)
MYSQL_PWD=$(docker exec $i env | grep MYSQL_ROOT_PASSWORD |cut -d"=" -f2-)
```

**Comment by dagistan-tuncbilek** [comment]
Thank you, i will use it.
